version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: jerobas-pg
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: jerobas-pg
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin@123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always


volumes:
  postgres_data:
